-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "Task_Started_Date" DROP NOT NULL,
ALTER COLUMN "Task_Completed_Date" DROP NOT NULL,
ALTER COLUMN "Task_Hours_Completed" DROP NOT NULL,
ALTER COLUMN "Task_Hidden_From_Client" DROP NOT NULL,
ALTER COLUMN "Person_Assigned_To_ID" DROP NOT NULL,
ALTER COLUMN "Task_Assigned_To_Name" DROP NOT NULL,
ALTER COLUMN "Created_Date" DROP NOT NULL,
ALTER COLUMN "Created_By" DROP NOT NULL,
ALTER COLUMN "Updated_Date" DROP NOT NULL,
ALTER COLUMN "Updated_By" DROP NOT NULL,
ALTER COLUMN "Total_Billable" DROP NOT NULL,
ALTER COLUMN "Total_Nonbillable" DROP NOT NULL;
