-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "Created_Date" DROP NOT NULL,
ALTER COLUMN "Created_By" DROP NOT NULL,
ALTER COLUMN "Updated_Date" DROP NOT NULL,
ALTER COLUMN "Updated_By" DROP NOT NULL;
