-- DropForeignKey
ALTER TABLE "Person" DROP CONSTRAINT "Person_Created_By_fkey";

-- DropForeignKey
ALTER TABLE "Person" DROP CONSTRAINT "Person_Updated_By_fkey";

-- AlterTable
ALTER TABLE "Person" ALTER COLUMN "Organization_ID" DROP NOT NULL,
ALTER COLUMN "Website_URL" DROP NOT NULL,
ALTER COLUMN "Logo_URL" DROP NOT NULL,
ALTER COLUMN "Address1_Mailing" DROP NOT NULL,
ALTER COLUMN "Address2_Mailing" DROP NOT NULL,
ALTER COLUMN "City_Mailing" DROP NOT NULL,
ALTER COLUMN "State_Mailing" DROP NOT NULL,
ALTER COLUMN "Zip_Mailing" DROP NOT NULL,
ALTER COLUMN "Address1_Physical" DROP NOT NULL,
ALTER COLUMN "Address2_Physical" DROP NOT NULL,
ALTER COLUMN "City_Physical" DROP NOT NULL,
ALTER COLUMN "State_Physical" DROP NOT NULL,
ALTER COLUMN "Zip_Physical" DROP NOT NULL,
ALTER COLUMN "Company_Profile" DROP NOT NULL,
ALTER COLUMN "Internal_Notes" DROP NOT NULL,
ALTER COLUMN "Owner_ID" DROP NOT NULL,
ALTER COLUMN "Primary_Contact_ID" DROP NOT NULL,
ALTER COLUMN "Accounting_ID" DROP NOT NULL,
ALTER COLUMN "Number_of_Employees" DROP NOT NULL,
ALTER COLUMN "Number_of_Contractors" DROP NOT NULL,
ALTER COLUMN "Created_Date" DROP NOT NULL,
ALTER COLUMN "Created_By" DROP NOT NULL,
ALTER COLUMN "Updated_Date" DROP NOT NULL,
ALTER COLUMN "Updated_By" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Person" ADD CONSTRAINT "Person_Created_By_fkey" FOREIGN KEY ("Created_By") REFERENCES "Person"("Person_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Person" ADD CONSTRAINT "Person_Updated_By_fkey" FOREIGN KEY ("Updated_By") REFERENCES "Person"("Person_ID") ON DELETE SET NULL ON UPDATE CASCADE;
