-- CreateTable
CREATE TABLE "Person" (
    "Organization_ID" INTEGER NOT NULL,
    "Status" TEXT NOT NULL,
    "Organization_Name" TEXT NOT NULL,
    "Organization_Type" TEXT NOT NULL,
    "Website_URL" TEXT NOT NULL,
    "Logo_URL" TEXT NOT NULL,
    "Address1_Mailing" TEXT NOT NULL,
    "Address2_Mailing" TEXT NOT NULL,
    "City_Mailing" TEXT NOT NULL,
    "State_Mailing" TEXT NOT NULL,
    "Zip_Mailing" TEXT NOT NULL,
    "Address1_Physical" TEXT NOT NULL,
    "Address2_Physical" TEXT NOT NULL,
    "City_Physical" TEXT NOT NULL,
    "State_Physical" TEXT NOT NULL,
    "Zip_Physical" TEXT NOT NULL,
    "Company_Profile" TEXT NOT NULL,
    "Internal_Notes" TEXT NOT NULL,
    "Owner_ID" INTEGER NOT NULL,
    "Owner_Name" TEXT NOT NULL,
    "Owner_Email" TEXT NOT NULL,
    "Owner_Phone" TEXT NOT NULL,
    "Primary_Contact_ID" INTEGER NOT NULL,
    "Primary_Name" TEXT NOT NULL,
    "Primary_Email" TEXT NOT NULL,
    "Primary_Phone" TEXT NOT NULL,
    "Accounting_ID" INTEGER NOT NULL,
    "Accounting_Name" TEXT NOT NULL,
    "Accounting_Email" TEXT NOT NULL,
    "Accounting_Phone" TEXT NOT NULL,
    "EIN" TEXT NOT NULL,
    "State_Tax_ID" TEXT NOT NULL,
    "Number_of_Employees" INTEGER NOT NULL,
    "Number_of_Contractors" INTEGER NOT NULL,
    "Created_Date" TIMESTAMP(3) NOT NULL,
    "Created_By" INTEGER NOT NULL,
    "Updated_Date" TIMESTAMP(3) NOT NULL,
    "Updated_By" INTEGER NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Person_Organization_ID_key" ON "Person"("Organization_ID");
