import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "./layoutComponents/AppBar";
import { Container, Grid } from "@mui/material";
import SideBar from "./layoutComponents/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Container>
          <Grid container spacing={2}>
              <Grid item xs={12} sm={12} md={12}>
                <AppBar />
              </Grid>
              <Grid item xs={3} sm={3} md={3}>
                <SideBar/>
              </Grid>
              <Grid item xs={9} sm={9} md={9}>
                <div className="content-window">
                  {children}
                </div>
              </Grid>
            </Grid>
            </Container>
        </body>
      </html>
    );
}
